name: Test

on: [push, pull_request]

jobs:
  end-to-end-test:
    runs-on: ubuntu-latest
    env:
      USER: user
      PASS: 123
      HOME_DIR: /home/user
      HOST: localhost
      FTP_PORT: 21
      FTPS_PORT: 81
    steps:
      - uses: actions/checkout@v2
      
      - name: Install vsftpd
        run: sudo apt-get update && sudo apt-get install -y vsftpd
      
      - name: Setup up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      
      - name: Update pip
        run: python -m pip install -U pip

      - run: pip install -U pytest

      - name: Run shell script
        run: sudo USER=$USER PASS=$PASS HOME_DIR=$HOME_DIR FTP_PORT=$FTP_PORT FTPS_PORT=$FTPS_PORT ./src/entrypoint.sh

      - name: Test FTP
        run: pytest ./tests/test_ftp.py

      - name: Test FTPS
        run: pytest ./tests/test_ftps.py